test: off
version: '0.3.4.{build}'
image: Visual Studio 2017

environment:
  my_pfx:
    secure: jxL/b1xngUepPiYC48vTzA==
    
branches:
  only:
  - master
  - develop
skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: true
  file: '**\netcore.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{build}'
  informational_version: '{version}'
  
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
      
install:
  # Install repo specific stuff here
  - ps: |
        Write-Host "Installing Windows SDK 2004 (10.0.19041.0)..." -ForegroundColor Cyan

        Write-Host "Downloading..."
        $exePath = "$env:temp\wdksetup.exe"
        (New-Object Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/p/?linkid=2120843', $exePath)

        Write-Host "Installing..."
        cmd /c start /wait $exePath /features + /quiet

        Remove-Item $exePath
        Write-Host "Installed" -ForegroundColor Green
        
  - ps: try { Import-PfxCertificate -FilePath .\examples\uwpapp\uwpapp_TemporaryKey.pfx -CertStoreLocation cert:\CurrentUser\My -Password (ConvertTo-SecureString $env:my_pfx -AsPlainText -Force) } catch {}

before_build:
  # Restore packages
  - cmd: echo %CD%
  - cmd: nuget restore ./fbchat-sharp.sln
  
build_script:
  # Build project
  cmd: msbuild /t:build /p:Configuration=Release /p:Platform=x64 ./fbchat-sharp.sln

after_build:
  - ps: .\examples\uwpapp\runAppcert.ps1 -target 'examples\uwpapp\AppPackages\uwpapp_1.0.0.0_Release_Test\uwpapp_1.0.0.0_x64_Release.appxbundle'
  - cmd: nuget pack ./fbchat-sharp/fbchat-sharp.nuspec
  - cmd: for /D %%x in (.\examples\uwpapp\AppPackages\uwpapp_*) do set "f=%%~fx"
  - cmd: 7z a example_uwp.zip %f%
  - cmd: 7z a example_wpf.zip .\examples\wpfapp\bin\Release

artifacts:
  - path: '*.nupkg'
  - path: 'example_uwp.zip'
  - path: 'example_wpf.zip'
    
deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    description: ''
    auth_token:
      secure: HzG3BylRrdqU49wZmjr6asVW70vqKv03uHai403G6PkHjpmD9s8C17IlpnxHPy8h # your encrypted token from GitHub
    artifact: /.*\.nupkg/,example_uwp.zip,example_wpf.zip
    draft: true
    prerelease: false
    force_update: true
    on:
      branch: master                    # release from master branch only
      appveyor_repo_tag: false          # deploy on non tag push only

  - provider: GitHub
    release: $(appveyor_build_version) beta
    description: ''
    auth_token:
      secure: HzG3BylRrdqU49wZmjr6asVW70vqKv03uHai403G6PkHjpmD9s8C17IlpnxHPy8h # your encrypted token from GitHub
    artifact: /.*\.nupkg/,example_uwp.zip,example_wpf.zip
    draft: true
    prerelease: true
    force_update: true
    on:
      branch: develop                   # pre-release from develop branch only
      appveyor_repo_tag: false          # deploy on non tag push only
